### ISSUE TITLE
get_latest_report.py giving an error

### ISSUE THREAD

**Issue by alainfi2016** [googleads/googleads-bidmanager-examples#1]
After creating a client_id, client secret in the google dbm api console and I tried to several times the "get_latest_report.py" but I get the following message:
Log into the Google Account you use to access your DBM accountand go to the following URL:
**https://accounts.google.com/o/oauth2/v2/auth?scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdoubleclickbidmanager&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&client_id=None&access_type=offline**

After login into the account and pasting the URL above, I get an error message 401 "invalid_client"
How would I get the code needed to continue the execution of this python sample?

**Comment by bo-brainlabs** [comment]
That URL is an auth URL supposed to help you authenticate. One of the params in the query string is the client_id=None. You need to set your client id in your authentication file. Probably an auth.ini somewhere. You probably also need to set your client secret, refresh token, and redirect uri. 

Sorry, I don't actually know where to find the documentation on authentication.

Once you authenticate though, all you need are the access and refresh tokens you get from the authentication process, and you can make requests with them.

``` php
$client = new Google_Client();
$client->setAuthConfigFile("client_secret.json");
$client->setAccessToken(FILE_WITH_ACCESS_AND_REFRESH_TOKEN_JSON);
$client->setAccessType('offline');
$client->addScope('https://www.googleapis.com/auth/doubleclickbidmanager');
```

You can download the client secret json file from the google developers console under your project. For example

``` php
$service = new Google_Service_DoubleClickBidManager($client);
$request = new Google_Service_DoubleClickBidManager_DownloadLineItemsRequest();
$result = $service->lineitems->downloadlineitems($request);
```

That's an example of downloading line items.
Getting a report is similar but more complicated.
Once you have the client though, you can use the service to get whatever you need.

**Comment by DeanLukies** [comment]
Hi,
take a look at https://github.com/googleads/googleads-bidmanager-examples/blob/master/python/README.md
Step 6 
You can set CLIENT_ID and CLIENT_SECRET in util.py
