### ISSUE TITLE
Count method expects an array or object

### ISSUE THREAD

**Issue by mertingen** [googleads/googleads-bidmanager-examples#10]
Once I download line items, I've been getting this unexpected error. **count(): Parameter must be an array or an object that implements Countable**

**Comment by jimper** [comment]
Hi there,

Could you clarify which sample this relates to and the specific line generating the error? If you can provide a sanitized log of the request and response leading up to this is would be helpful.

Regards,
\- Jonathon Imperiosi, DBM API Team

**Comment by mertingen** [comment]
Hi Jonathon,

I use action which is the **DownloadItems**. This error occurs on the 59th
line examples/DownloadItems.php.

**if (!isset($result['lineItems']) || count($result['lineItems']) < 1) {**

Here, the count method expects an array or an object but the string is
coming.

**Comment by jimper** [comment]
Thanks for the additional info. Can you try modifying that line to:

if (empty($result['lineItems'])) {

And let me know if you're still getting an error?

**Comment by mertingen** [comment]
In fact, I've changed the following:

if (!isset($result['lineItems']) || mb_strlen($result['lineItems']) < 1) {

It's beautiful with this. In addition to this, I tried as you mentioned.
Likewise, it's working correctly.

**Comment by jimper** [comment]
Thanks for confirming, I'll update the samples to remove count(). Since the value is always a string that check isn't even necessary. All we need to verify is that the field exists and is non-empty.

**Comment by mertingen** [comment]
I totally understood. Thanks a lot!
