### ISSUE TITLE
Insufficient Permission Error while executing the code on GCP VM Instance

### ISSUE THREAD

**Issue by sedhha** [googleads/googleads-bidmanager-examples#16]
I have been trying to execute GCP Bid manager API in GCP virtual instance but I get this error:

> HttpError 403 when requesting https://********** returned "Insufficient Permission: Request had insufficient authentication scopes.

Tried to resolve it using:

> gcloud auth login

But this doesn't work as well. I have all the credential json file with the name clien_secrets.json.

**Comment by tmulchay** [comment]
Hi,

Are you making sure that the proper DBM authentication scope (example: https://www.googleapis.com/auth/doubleclickbidmanager) is included in your authentication process? 

Thank you,
Trevor Mulchay, DBM API Team

**Comment by sedhha** [comment]
Resolved the issue, it was arising due to wrong secret_credentials.json file!
