### ISSUE TITLE
Google_Service_DoubleClickBidManager_DownloadLineItemsRequest Not Found

### ISSUE THREAD

**Issue by RecruboMark** [googleads/googleads-bidmanager-examples#21]
A couple of days ago i was looking in to our Google Display & Video 360 reports. I noticed they stopped reporting data because of the error: 
Class 'Google_Service_DoubleClickBidManager_DownloadRequest' not found

After some investigation i found your examples which were using 'Google_Service_DoubleClickBidManager_DownloadLineItemsRequest'.

I probably missed some updates and updated my code according to the line item example in this repo.
After updating my code i got the same error with the updated class name.

I have imported the required packages and am using Laravel so they are automaticly added to the autoloader.
![afbeelding](https://user-images.githubusercontent.com/52448924/139700163-66653753-e067-48c6-aac9-38a658ee746c.png)

Is this example outdated? 

Some extra info about my project;
I manage a project which pull data from many different marketing platforms. 
For Google DV 360 we pull all insertion orders, line items and creatives in seperate calls and save them to our database.
After pulling all dimension data we pull some metrics like impressions, clicks and spend.
All this data used to be pulled through the Doubleclick manager package from the google php client.

I can supply some code samples if required, i would have to recreate them after migrating the implementation to the Google Display & Video php client. 
The DV360 client does not fullfill my needs because it prepares zipped CSV documents which are hard to work with in code.

Thanks in advance.

**Comment by tmulchay** [comment]
Hi,

The DBM API's [lineItems](https://developers.google.com/bid-manager/v1.1/lineitems) and [sdf](https://developers.google.com/bid-manager/v1.1/sdf) services were [deprecated in August 2020](https://ads-developers.googleblog.com/2020/08/sunset-of-dbm-api-v1-sdf-download-and.html) and [sunset in April 2021](https://developers.google.com/bid-manager/change-log#2021-04-15). All requests now made to these services will return an error.

I would recommend using the new [Display & Video 360 API](https://developers.google.com/display-video/api/guides/getting-started/overview) as a replacement for these sunset endpoints. The DV360 API supports [downloading Structured Data Files](https://developers.google.com/display-video/api/guides/downloading-sdfs/create) and retrieving, creating, and updating entities such as [line items](https://developers.google.com/display-video/api/reference/rest/v1/advertisers.lineItems), [insertion orders](https://developers.google.com/display-video/api/reference/rest/v1/advertisers.insertionOrders), and [creatives](https://developers.google.com/display-video/api/reference/rest/v1/advertisers.creatives).

Thank you,
Trevor Mulchay, DBM API Team
