### ISSUE TITLE
Doubleclick for bid manager CreateQuery stopped working

### ISSUE THREAD

**Issue by aonurbilgin** [googleads/googleads-bidmanager-examples#3]
I have been using the following query for the CreateQuery API in Doubleclick for Bid Manager successfully. But it has stopped working since first day of September with the error:
`[Google_Service_Exception]             
  {                                      
   "error": {                            
    "errors": [                          
     {                                   
      "domain": "global",                
      "reason": "invalid",               
      "message": "Invalid Value",        
      "locationType": "other",           
      "location": "params.filter.value"  
     }                                   
    ],                                   
    "code": 400,                         
    "message": "Invalid Value"           
   }                                     
  }                                      
     `
I have only one filter for the request. Its FILTER_ADVERTISER without value. So that way i can download all clients report in partner. But that way not working anymore first day of September.

There is nothing about it why its not working ? :(

**Comment by jimper** [comment]
Hi there, it sounds like you're saying that you're trying to create a query which contains an advertiser filter without a value? If so, that would be the cause of the error. Every filter you include is required to specify a value. If you want to allow all possible values in the report, you can just not specify any filter at all.

**Comment by aonurbilgin** [comment]
Hi, If I remove the filter (we don't actually want to filter out any data) it will error that "At least one of FILTER_PARTNER or FILTER_ADVERTISER must be set."

**Comment by jimper** [comment]
Hi there, from your previous description of the situation it sounds like you'd want to set a partner filter in this case. If you still have questions about how to configure your report, the [DBM support team](https://developers.google.com/bid-manager/get-support) can help.
