### ISSUE TITLE
dbm_sample.yaml

### ISSUE THREAD

**Issue by razadera** [googleads/googleads-bidmanager-examples#4]
Should there be a dbm_sample.yaml file within this repository? It is required to hold the client_id and client_secret but I don't see it in this repository. 

Thanks!
Ryan

**Comment by jimper** [comment]
Hi Ryan,

The contents of dbm_sample.yaml contain sensitive info that should not be shared. It's used as a data store to cache access/refresh tokens, as well as the client ID/secret used to generate them. The file will be auto-generated the first time you successfully authorize a sample request.

To get started using the samples, you should follow the instructions from the README:

> You will only need to authorize once to run these samples. You can either open util.py and manually enter the CLIENT_ID and CLIENT_SECRET fields or you may provide them as command line arguments when running one of the samples. By default, your credentials will be saved to dbm_sample.yaml in your home directory.

Regards,
-- Jonathon Imperiosi, DBM API Team

**Comment by razadera** [comment]
Thanks Jonathon. I didn't realize the dbm_sample.yaml file would auto-generate. I'm still having an issue successfully authenticating a sample api pull. I have tried running the download_line_items.py script with the client id and client secret both as command line arguments and by manually entering them in the util.py script, but I am not getting a prompt to enter a refresh token as I would expect. 

I'm getting the error "NameError: name 'raw_input' is not defined", which I see is because I am not entering a refresh token because it is not prompting me. Any help on this? 

Thanks,
Ryan

**Comment by jimper** [comment]
Hi Ryan,

That error is saying the raw_input function isn't defined. I assume you're using Python v3.x, which renamed raw_input -> input (this code was written against Python v2.x). You could try changing that line to call input() instead and see if it resolves the issue.

Regards,
-- Jonathon Imperiosi, DBM API Team

**Comment by razadera** [comment]
Hey Jonathon,

Thanks so much! That did the trick. I also had to remove binary mode from the open() commands.
