### ISSUE TITLE
[Python] Default Credentials will never be used

### ISSUE THREAD

**Issue by msaniscalchi** [googleads/googleads-bidmanager-examples#6]
Default credentials configured in **util.py** will never be used because `path` will always evaluate `True` in `get_service()` on [this line](https://github.com/googleads/googleads-bidmanager-examples/blob/master/python/util.py#L153).

Work-around is to provide credentials as an argument when running the examples.

**Comment by jimper** [comment]
We really shouldn't be encouraging users to hardcode their credentials, so it's probably better to remove support for that completely.
