### ISSUE TITLE
DownloadOrderDetails

### ISSUE THREAD

**Issue by kdotzenrod517** [googleads/googleads-bidmanager-examples#8]
Is there an available service to retrieve order details, similar to the service available for downloading line items?

`POST https://www.googleapis.com/doubleclickbidmanager/v1/lineitems/downloadlineitems`

Thanks

**Comment by jimper** [comment]
Hi there,

All available services are documented at [https://developers.google.com/bid-manager/v1/](). If you have additional questions, feel free to follow up with our API support team at [dbmapi-support@google.com](mailto:dbmapi-support@google.com). This tracker is only for issues with the API code samples, but our support team is equipped to answer more general API questions.

Regards,
\- Jonathon Imperiosi, DBM API Team
