### ISSUE TITLE
Issue with the method getLatestReport

### ISSUE THREAD

**Issue by SandeepMT** [googleads/googleads-bidmanager-examples#9]
Hi ,

I am facing one issue with the getLatestReport method which is providing the URL for the second latest report not the recent one. Does anybody facing the same issue.  Any solution will be appreciated.

**Comment by jimper** [comment]
Hi there,

It sounds like the most recent report might not be finished running yet. The value of [metadata.googleCloudStoragePathForLatestReport](https://developers.google.com/bid-manager/v1/queries#metadata.googleCloudStoragePathForLatestReport) always contains the URL for the most recently completed report run. If [metadata.running](https://developers.google.com/bid-manager/v1/queries#metadata.running) is true, the most recent report run isn't finished, so the URL will point to data from the previous run.

If this isn't the case or you have any other questions not directly related to the examples in this repo, please follow up with our [support team](https://developers.google.com/bid-manager/get-support).

\- Jonathon Imperiosi, DBM API Team
